// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbmkvhmloopuzqqnzcdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhibWt2aG1sb29wdXpxcW56Y2RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTgzOTksImV4cCI6MjA2NTU3NDM5OX0.tavE21ykDTLgByASZt4FjwvLqDTxSCFhCFD1y6HZZ8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);